---
# configure Antora for a local test using the published UI bundle

site:
  title: The Minie project (local test using the published bundle)
  start_page: minie:ROOT:overview.adoc
  url: /home/sgold/NetBeansProjects/Minie/build/site
content:
  sources:
    - url: /home/sgold/NetBeansProjects/Minie
      branches: master
      start_path: src/site/antora/minie-project
    - url: /home/sgold/NetBeansProjects/Minie
      branches: master
      start_path: MinieLibrary/src/site/antora/tutorials
ui:
  bundle:
    url: https://github.com/stephengold/antora-ui-bundle/releases/download/v-sgold230101a/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: build/site
